# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphs', '0003_auto_20170114_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordcount',
            unique_together=set([('date', 'user')]),
        ),
    ]
